transactionCoordinatorEnabled=true
transactionMetadataStoreProviderClassName=org.apache.pulsar.transaction.coordinator.impl.MLTransactionMetadataStoreProvider
transactionBufferSnapshotMaxTransactionCount=1000
transactionBufferSnapshotMinTimeInMillis=5000
transactionBufferSegmentedSnapshotEnabled=false
transactionBufferSnapshotSegmentSize=262144
transactionBufferClientMaxConcurrentRequests=1000
transactionPendingAckLogIndexMinLag=500
transactionBufferClientOperationTimeoutInMills=3000
transactionLogBatchedWriteEnabled=true
transactionLogBatchedWriteMaxRecords=512
transactionLogBatchedWriteMaxSize=4194304
transactionLogBatchedWriteMaxDelayInMillis=1
transactionPendingAckBatchedWriteEnabled=true
transactionPendingAckBatchedWriteMaxRecords=512
transactionPendingAckBatchedWriteMaxSize=4194304
transactionPendingAckBatchedWriteMaxDelayInMillis=1
