import type { Breadcrumb } from "@cloudflare/nimbus-docs/types";

const trimSlashes = (path: string) => path.replace(/^\/+|\/+$/g, "");

/**
 * Link each section crumb to its section's front page.
 *
 * The sidebar shows a section's `index.mdx` as an "Overview" leaf inside its
 * group (`indexDisplay: "overview-leaf"` in astro.config.ts), so the group has
 * no URL of its own and `getBreadcrumbs` returns its crumb without an `href`:
 * "Home / Concepts / Transactions" with "Concepts" a dead span. A reader had no
 * way up, and every page's BreadcrumbList was invalid for Google, which needs
 * an `item` URL on every crumb but the last.
 *
 * The sidebar is autogenerated from directories, so the crumb at depth `i`
 * stands for the first `i` segments of the URL. It is linked to that prefix
 * when a page exists there. On the section's own front page that would read
 * "Concepts / Overview" with both crumbs on one URL, so the "Overview" crumb is
 * dropped and the section crumb is the current page.
 */
export function linkSectionCrumbs(
  crumbs: Breadcrumb[],
  pathname: string,
  pageExists: (id: string) => boolean,
): Breadcrumb[] {
  const segments = trimSlashes(pathname).split("/").filter(Boolean);
  const linked = crumbs.map((crumb, i) => {
    if (crumb.href || i === 0 || i === crumbs.length - 1) return crumb;
    const id = segments.slice(0, i).join("/");
    return id && pageExists(id) ? { ...crumb, href: `/${id}/` } : crumb;
  });
  return linked.filter((crumb, i) => {
    const previous = linked[i - 1]?.href;
    return !crumb.href || !previous || trimSlashes(crumb.href) !== trimSlashes(previous);
  });
}
