"""Turn the verdict lines from a run into MATRIX.md.

MATRIX.md is generated, not edited: it is the RECORD of one run, and a hand-edit
in it would be a claim nobody measured. Prose that belongs to the lane rather
than to a run lives here, in the generator.
"""

import json
import sys
from datetime import datetime, timezone

CELLS = [
    ("jsonl", "zstd"),
    ("jsonl", "gzip"),
    ("jsonl", "none"),
    ("parquet", "zstd"),
    ("parquet", "snappy"),
]
CELL_LABEL = {
    ("jsonl", "zstd"): "jsonl<br>zstd",
    ("jsonl", "gzip"): "jsonl<br>gzip",
    ("jsonl", "none"): "jsonl<br>plain",
    ("parquet", "zstd"): "parquet<br>zstd",
    ("parquet", "snappy"): "parquet<br>snappy",
}
ORDER = ["duckdb", "clickhouse", "spark", "polars", "pyarrow", "pandas", "trino"]
TITLE = {
    "duckdb": "DuckDB",
    "clickhouse": "ClickHouse",
    "spark": "Apache Spark (PySpark)",
    "polars": "Polars",
    "pyarrow": "PyArrow",
    "pandas": "pandas",
    "trino": "Trino (the Athena shape)",
}

HEADER = """# queen-s3 reader compatibility matrix

Which real lake readers read what the sink writes, and with which incantation.
Every row is a real reader, at the version in its row, opening objects produced
by the connector's OWN writers (`cargo run --example gen_samples`) — nothing in
this file is a claim about a format, it is a measurement of a reader against
bytes `queen_s3::writer` produced.

**Generated by `compat/run.sh`. Do not edit it by hand** — see
[README.md](README.md) for what it does and does not assert.

`ok` means the reader opened the prefix AND was exact: the record count per queue
and per partition, the number of NULL payloads, and the sha256 of the
`partition|offset` list **in the order the reader's own
`ORDER BY partition, offset` returned it**, all against `expected.json`. Anything
less than that is not `ok`. `unsupported` is a documented fact about the reader
(a codec it does not have), not a failure of the sink. `not-run` is an
admission.

The **queue name is not in the rows** — it is the `queue=<esc>` key of the path
(plan §6.3, §6.4) — so every `ok` below also means the reader recovered it from
the layout: through partition discovery where it has any, and otherwise by being
pointed at one queue's prefix. The incantations say which."""

FOOTER_TRINO = """## Trino / Athena — not run

The Trino row was **not measured** and its cells say `not-run`. A container was
stood up far enough to learn four things that anyone writing the Athena DDL will
meet, and they are recorded here because they are real, but no exactness check
was ever run and the DDL below is **untested**:

1. `hive.timestamp-precision` defaults to `MILLISECONDS`, and the connector then
   REFUSES a `timestamp(6)` column: `Incorrect timestamp precision for
   timestamp(6); the configured precision is MILLISECONDS`. The sink writes
   `TIMESTAMP(MICROS,UTC)`, so the catalog needs
   `hive.timestamp-precision=MICROSECONDS` or the table has to declare
   `timestamp(3)` and drop three digits of the broker's clock.
2. A Hive table may not repeat a column name, so `queue` could never be both a
   `queue=` partition key and a data column. It is now only the key (plan §6.3,
   §6.4): the DDL below declares the file's five columns, points
   `external_location` at ONE queue's prefix and partitions by `dt`/`hour`,
   which is the natural modelling anyway (a table per queue). Pointing the table
   at the layout root instead and adding `queue` to `partitioned_by` — Hive
   wants partition columns last, in order — is the other shape, and it is the
   one Athena's projection template below writes.
3. On Trino 483 `fs.native-local.enabled` is renamed `fs.local.enabled`, and the
   local file system has a root (`local.location`, default `/tmp`) that every
   location is resolved against.
4. `partition` and `offset` are reserved words and must be quoted throughout.

```sql
-- UNTESTED. The Athena shape, with partition projection instead of a metastore.
-- No `queue` column: it is the path key, and this table IS one queue.
CREATE TABLE queen_orders (
  "partition"     varchar,
  "offset"        bigint,
  transaction_id  varchar,
  ts              timestamp(6),        -- needs hive.timestamp-precision=MICROSECONDS
  payload         varchar              -- JSON text; json_extract_scalar(payload, '$.type')
)
WITH (
  external_location = 's3://lake/queen/queue=orders/',
  format            = 'PARQUET',
  partitioned_by    = ARRAY['dt', 'hour']
);
CALL system.sync_partition_metadata('lake', 'queen_orders', 'ADD');

-- Athena, same layout, no metastore sync: partition projection over the two keys
-- the sink's alignment guarantees are exact (plan §4.4).
--   'projection.enabled'      = 'true',
--   'projection.dt.type'      = 'date',
--   'projection.dt.range'     = '2026-01-01,NOW',
--   'projection.dt.format'    = 'yyyy-MM-dd',
--   'projection.hour.type'    = 'integer',
--   'projection.hour.range'   = '0,23',
--   'projection.hour.digits'  = '2',
--   'storage.location.template' = 's3://lake/queen/queue=orders/dt=${dt}/hour=${hour}/'
```
"""


def main():
    verdicts_path, expected_path, out_path = sys.argv[1:4]
    verdicts, notes = [], []
    with open(verdicts_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line.startswith("VERDICT "):
                verdicts.append(json.loads(line[8:]))
            elif line.startswith("NOTE "):
                notes.append(json.loads(line[5:]))
    with open(expected_path, encoding="utf-8") as f:
        exp = json.load(f)

    by_reader = {}
    for v in verdicts:
        by_reader.setdefault(v["reader"], {})[(v["format"], v["compression"])] = v
    readers = [r for r in ORDER if r in by_reader] + sorted(
        r for r in by_reader if r not in ORDER
    )

    out = [HEADER, ""]
    out.append(
        "Measured %s against %d records in each of the five prefixes "
        "(2 queues, 3 partitions each, 2 aligned hour windows, %d objects per "
        "prefix, Parquet row groups of %d rows).\n"
        % (
            datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            exp["records"],
            len(exp["prefixes"]["parquet-zstd"]["objects"]),
            exp["writerPins"]["parquetRowGroupRecords"],
        )
    )

    # -- the table ----------------------------------------------------------
    out.append("## The matrix\n")
    out.append(
        "| Reader | Version | " + " | ".join(CELL_LABEL[c] for c in CELLS) + " |"
    )
    out.append("| --- | --- | " + " | ".join("---" for _ in CELLS) + " |")
    for r in readers:
        cells = []
        for c in CELLS:
            v = by_reader[r].get(c)
            cells.append(short(v["verdict"]) if v else "—")
        version = next(iter(by_reader[r].values()))["version"]
        out.append("| %s | %s | %s |" % (TITLE.get(r, r), version, " | ".join(cells)))
    out.append("")

    # -- the incantations ---------------------------------------------------
    out.append("## The incantation that worked\n")
    out.append(
        "One line per distinct call. `<prefix>` is the directory holding one "
        "(format, compression), e.g. `s3://lake/queen/`; the sink's own keys "
        "(`queue=/dt=/hour=/w-<k>-<tStart>-<tEnd>.<ext>`) are below it.\n"
    )
    for r in readers:
        rows = [by_reader[r][c] for c in CELLS if c in by_reader[r]]
        seen = []
        for v in rows:
            key = v["incantation"]
            for s in seen:
                # (call, kind): one call that is `ok` for two cells and
                # `unsupported` for a third must not print as one line.
                if s["call"] == key and s["verdict"].split(":")[0] == v["verdict"].split(":")[0]:
                    s["cells"].append("%s/%s" % (v["format"], v["compression"]))
                    break
            else:
                seen.append(
                    {
                        "call": key,
                        "cells": ["%s/%s" % (v["format"], v["compression"])],
                        "verdict": v["verdict"],
                    }
                )
        out.append("**%s**\n" % TITLE.get(r, r))
        for s in seen:
            out.append("- `%s`  \n  %s — %s" % (s["call"], ", ".join(s["cells"]), short(s["verdict"])))
        out.append("")

    # -- what is not ok -----------------------------------------------------
    bad = [
        v
        for v in verdicts
        if not v["verdict"].startswith("ok")
    ]
    out.append("## Every cell that is not `ok`\n")
    if not bad:
        out.append("None.\n")
    else:
        out.append("| Reader | Cell | Verdict | Why |")
        out.append("| --- | --- | --- | --- |")
        for v in sorted(bad, key=lambda v: (v["reader"], v["format"], v["compression"])):
            kind, _, reason = v["verdict"].partition(":")
            why = reason or v.get("detail", "")
            out.append(
                "| %s | %s/%s | `%s` | %s |"
                % (
                    TITLE.get(v["reader"], v["reader"]),
                    v["format"],
                    v["compression"],
                    kind,
                    md(why or "—"),
                )
            )
        out.append("")

    # -- notes --------------------------------------------------------------
    if notes:
        out.append("## What the readers disagree about\n")
        for r in readers:
            mine = [n for n in notes if n["reader"] == r]
            if not mine:
                continue
            out.append("**%s**\n" % TITLE.get(r, r))
            for n in mine:
                out.append("- %s" % md(n["text"]))
            out.append("")

    out.append(FOOTER_TRINO)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out).rstrip() + "\n")
    print("wrote %s (%d verdicts, %d notes)" % (out_path, len(verdicts), len(notes)))


def short(verdict):
    kind, _, reason = verdict.partition(":")
    if kind == "ok":
        return "ok"
    if kind == "not-run":
        return "not-run"
    return "**%s**" % kind


def md(text):
    return text.replace("|", "\\|").replace("\n", " ")


if __name__ == "__main__":
    main()
