import { defineConfig } from "astro/config";
import icon from "astro-icon";
import tailwindcss from "@tailwindcss/vite";
import nimbus, { defineConfig as defineNimbusConfig } from "@cloudflare/nimbus-docs";
import { tableScroll } from "@cloudflare/nimbus-docs/markdown";

const nimbusConfig = defineNimbusConfig({
  site: "https://queenmq.com",
  title: "Queen MQ",
  description:
    "Ordered FIFO partitions and consumer groups on the PostgreSQL you already run — one stateless binary, no cluster to operate.",
  locale: "en",
  homeLabel: "Queen MQ",
  github: "https://github.com/queen-mq/queen",
  editPattern: "https://github.com/queen-mq/queen/edit/master/webdoc/{path}",
  socialImageAlt: "Queen MQ documentation",
  // Brand assets are generated by assets/generate-brand.py from the two
  // hand-made master line-marks — webdoc/public is one of its output surfaces.
  // The SVG favicon is theme-adaptive; the .ico the scaffold ships stays as the
  // fallback for browsers that ignore SVG icons.
  head: [
    { tag: "link", attrs: { rel: "icon", type: "image/svg+xml", href: "/favicon.svg" } },
    { tag: "link", attrs: { rel: "apple-touch-icon", href: "/apple-touch-icon.png" } },
  ],
  sidebar: {
    // The whole tree in every rail, with groups collapsed. Section-scoped rails
    // read shorter, but they hide the rest of the site behind the header tabs —
    // a reader who does not know a section exists never opens it. Six collapsed
    // groups fit on screen, and the group holding the current page opens itself.
    scope: "full",
    defaultCollapsed: true,
    overviewLabel: "Overview",
    indexDisplay: "overview-leaf",
    items: [
      { label: "Start here", icon: "ph:rocket-launch", autogenerate: { directory: "start" } },
      { label: "Use Queen", icon: "ph:code", autogenerate: { directory: "use" } },
      { label: "Reference", icon: "ph:book-open-text", autogenerate: { directory: "reference" } },
      { label: "Self-hosting", icon: "ph:hard-drives", autogenerate: { directory: "selfhost" } },
      { label: "Internals", icon: "ph:cpu", autogenerate: { directory: "internals" } },
      { label: "Benchmarks", icon: "ph:chart-line-up", autogenerate: { directory: "benchmarks" } },
    ],
  },
});

export default defineConfig({
  // Static output: `pnpm build` emits dist/, which Cloudflare Pages serves
  // directly (build command `pnpm build`, output directory `dist`).
  output: "static",
  // Tailwind v4 via its Vite plugin (the integration Astro recommends for
  // Tailwind v4 — replaces the PostCSS plugin, which doesn't build under
  // Astro 7's Vite 8 bundler).
  vite: {
    plugins: [tailwindcss()],
  },
  // Hover-prefetch link targets so full-page navigations feel instant without
  // a client-side router.
  prefetch: {
    prefetchAll: true,
    defaultStrategy: "hover",
  },
  integrations: [
    icon(),
    nimbus(nimbusConfig, {
      // Every rule that can catch a structural or factual regression is an
      // error. Large parts of this site are generated from source code and
      // cross-linked to it, so a broken link or a malformed frontmatter
      // block usually means a page has drifted from what it documents.
      rules: {
        "nimbus/frontmatter-shape": "error",
        // The generated OpenAPI documents are static assets under public/, not
        // pages, so the route map the rule checks against does not contain
        // them. Everything else must resolve to a real page.
        "nimbus/internal-link": ["error", { ignore: ["/openapi/**"] }],
        "nimbus/description-required": "error",
        "nimbus/single-h1": "error",
        "nimbus/heading-hierarchy": "error",
        "nimbus/code-block-lang": "error",
        "nimbus/code-block-prompt-prefix": "error",
        "nimbus/no-self-host-url": "error",
        "nimbus/image-ref": "error",
        "nimbus/duplicate-heading-text": "warn",
        "nimbus/heading-punctuation": "warn",
        "nimbus/bare-url": "warn",
      },
      // Wrap wide tables so they scroll instead of overflowing the page
      // (styled by `.nb-table-scroll` in src/styles/prose.css).
      markdown: {
        hastPlugins: [tableScroll()],
      },
    }),
  ],
});
