import { defineConfig } from "astro/config";
import icon from "astro-icon";
import tailwindcss from "@tailwindcss/vite";
import nimbus, { defineConfig as defineNimbusConfig } from "@cloudflare/nimbus-docs";
import { tableScroll } from "@cloudflare/nimbus-docs/markdown";

// Site-wide structured data. Nothing else on the site states what this
// software is, so the framework's WebSite node is the only machine-readable
// claim; these three add the software itself, its source and its publisher.
// Deliberately no `softwareVersion`: the repository and the registries
// disagree on it, and a hardcoded version here goes stale without failing
// anything. `softwareRequirements` follows selfhost/postgres.mdx, where the
// floor is 15 (14 fails on the `NULLS NOT DISTINCT` index).
const structuredData = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "https://queenmq.com/#org",
      name: "Queen MQ",
      url: "https://queenmq.com/",
      logo: "https://queenmq.com/queen-tile.png",
      sameAs: ["https://github.com/queen-mq/queen"],
    },
    {
      "@type": "SoftwareApplication",
      "@id": "https://queenmq.com/#software",
      name: "Queen MQ",
      applicationCategory: "DeveloperApplication",
      applicationSubCategory: "Message broker",
      operatingSystem: "Linux",
      programmingLanguage: "Rust",
      softwareRequirements: "PostgreSQL 15+",
      license: "https://www.apache.org/licenses/LICENSE-2.0",
      downloadUrl: "https://ghcr.io/queen-mq/queen",
      url: "https://queenmq.com/",
      author: { "@id": "https://queenmq.com/#org" },
      offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    },
    {
      "@type": "SoftwareSourceCode",
      "@id": "https://queenmq.com/#source",
      codeRepository: "https://github.com/queen-mq/queen",
      programmingLanguage: "Rust",
      license: "https://www.apache.org/licenses/LICENSE-2.0",
      about: { "@id": "https://queenmq.com/#software" },
    },
  ],
};

const nimbusConfig = defineNimbusConfig({
  site: "https://queenmq.com",
  title: "Queen MQ",
  description:
    "A message queue on the PostgreSQL you already run: one ordered FIFO lane per entity, consumer groups, replay, a dead-letter queue and a dashboard, in one binary.",
  locale: "en",
  homeLabel: "Queen MQ",
  github: "https://github.com/queen-mq/queen",
  editPattern: "https://github.com/queen-mq/queen/edit/master/webdoc/{path}",
  socialImageAlt: "Queen MQ documentation",
  // Brand assets are generated by assets/generate-brand.py from the two
  // hand-made master logos — webdoc/public is one of its output surfaces.
  // The favicon is the black-disc logo (reads on light and dark tab strips).
  // No `rel="icon"` entry here: NimbusHead already emits one for whichever of
  // favicon.svg / .ico / .png it finds in public/, and repeating it produced
  // two identical <link> tags on every page.
  head: [
    { tag: "link", attrs: { rel: "apple-touch-icon", href: "/apple-touch-icon.png" } },
    {
      tag: "script",
      attrs: { type: "application/ld+json" },
      content: JSON.stringify(structuredData),
    },
  ],
  sidebar: {
    // The whole tree in every rail, with groups collapsed. Section-scoped rails
    // read shorter, but they hide the rest of the site behind the header tabs —
    // a reader who does not know a section exists never opens it. Six collapsed
    // groups fit on screen, and the group holding the current page opens itself.
    scope: "full",
    defaultCollapsed: true,
    overviewLabel: "Overview",
    indexDisplay: "overview-leaf",
    items: [
      { label: "Start here", icon: "ph:rocket-launch", autogenerate: { directory: "start" } },
      { label: "Use Queen", icon: "ph:code", autogenerate: { directory: "use" } },
      {
        label: "Full examples",
        icon: "ph:file-code",
        autogenerate: { directory: "full-examples" },
      },
      { label: "Reference", icon: "ph:book-open-text", autogenerate: { directory: "reference" } },
      { label: "Self-hosting", icon: "ph:hard-drives", autogenerate: { directory: "selfhost" } },
      { label: "Internals", icon: "ph:cpu", autogenerate: { directory: "internals" } },
      { label: "Benchmarks", icon: "ph:chart-line-up", autogenerate: { directory: "benchmarks" } },
    ],
  },
});

export default defineConfig({
  // Static output: `pnpm build` emits dist/, which Cloudflare Pages serves
  // directly (build command `pnpm build`, output directory `dist`).
  output: "static",
  // Tailwind v4 via its Vite plugin (the integration Astro recommends for
  // Tailwind v4 — replaces the PostCSS plugin, which doesn't build under
  // Astro 7's Vite 8 bundler).
  vite: {
    plugins: [tailwindcss()],
  },
  // Hover-prefetch link targets so full-page navigations feel instant without
  // a client-side router.
  prefetch: {
    prefetchAll: true,
    defaultStrategy: "hover",
  },
  integrations: [
    icon(),
    nimbus(nimbusConfig, {
      // Every rule that can catch a structural or factual regression is an
      // error. Large parts of this site are generated from source code and
      // cross-linked to it, so a broken link or a malformed frontmatter
      // block usually means a page has drifted from what it documents.
      rules: {
        "nimbus/frontmatter-shape": "error",
        // The generated OpenAPI documents are static assets under public/, not
        // pages, so the route map the rule checks against does not contain
        // them. Everything else must resolve to a real page.
        "nimbus/internal-link": ["error", { ignore: ["/openapi/**"] }],
        "nimbus/description-required": "error",
        "nimbus/single-h1": "error",
        "nimbus/heading-hierarchy": "error",
        "nimbus/code-block-lang": "error",
        "nimbus/code-block-prompt-prefix": "error",
        "nimbus/no-self-host-url": "error",
        "nimbus/image-ref": "error",
        "nimbus/duplicate-heading-text": "warn",
        "nimbus/heading-punctuation": "warn",
        "nimbus/bare-url": "warn",
      },
      // Wrap wide tables so they scroll instead of overflowing the page
      // (styled by `.nb-table-scroll` in src/styles/prose.css).
      markdown: {
        hastPlugins: [tableScroll()],
      },
    }),
  ],
});
