//! The golden fixtures (§5.1: "every kind has fixture bytes under
//! `rsm/tests/golden/`; a change to a golden file is a format change and needs
//! a kind version bump").
//!
//! One file per effect kind plus one whole entry. The test compares the bytes
//! the current build produces with the bytes on disk, BOTH ways: it encodes
//! the sample and compares, and it decodes the file and compares the value. A
//! decoder that drifted apart from the encoder would pass only the first.
//!
//! To rewrite the fixtures after a DELIBERATE format change (and a version
//! bump), run:
//!
//! ```text
//! QUEEN_RSM_GOLDEN_UPDATE=1 cargo test -p queen-engine --lib rsm::tests::golden
//! ```
//!
//! That run FAILS on purpose after rewriting them, so a fixture can never be
//! silently regenerated by a normal test run or by CI with the variable set.

use super::samples::*;
use crate::rsm::effect::*;
use crate::rsm::entry::*;

/// The fixture bytes of one kind. `include_bytes!` resolves relative to THIS
/// file, and a missing file is a compile error — so a kind added to the
/// catalogue cannot ship without a fixture.
fn fixture(kind: Kind) -> &'static [u8] {
    match kind {
        Kind::Noop => include_bytes!("golden/effect_noop.bin"),
        Kind::QueueUpsert => include_bytes!("golden/effect_queue_upsert.bin"),
        Kind::QueueDelete => include_bytes!("golden/effect_queue_delete.bin"),
        Kind::GroupUpsert => include_bytes!("golden/effect_group_upsert.bin"),
        Kind::GroupDelete => include_bytes!("golden/effect_group_delete.bin"),
        Kind::PartitionCreate => include_bytes!("golden/effect_partition_create.bin"),
        Kind::PartitionDelete => include_bytes!("golden/effect_partition_delete.bin"),
        Kind::Append => include_bytes!("golden/effect_append.bin"),
        Kind::CursorSet => include_bytes!("golden/effect_cursor_set.bin"),
        Kind::CursorDelete => include_bytes!("golden/effect_cursor_delete.bin"),
        Kind::DlqInsert => include_bytes!("golden/effect_dlq_insert.bin"),
        Kind::DlqDelete => include_bytes!("golden/effect_dlq_delete.bin"),
        Kind::Watermark => include_bytes!("golden/effect_watermark.bin"),
        Kind::KvPut => include_bytes!("golden/effect_kv_put.bin"),
        Kind::KvDelete => include_bytes!("golden/effect_kv_delete.bin"),
        Kind::TimerUpsert => include_bytes!("golden/effect_timer_upsert.bin"),
        Kind::TimerDelete => include_bytes!("golden/effect_timer_delete.bin"),
        Kind::TimerBackoff => include_bytes!("golden/effect_timer_backoff.bin"),
        Kind::StreamsQueryUpsert => include_bytes!("golden/effect_streams_query_upsert.bin"),
        Kind::StreamsStatePut => include_bytes!("golden/effect_streams_state_put.bin"),
        Kind::StreamsStateDelete => include_bytes!("golden/effect_streams_state_delete.bin"),
        Kind::TraceAppend => include_bytes!("golden/effect_trace_append.bin"),
        Kind::TraceExpire => include_bytes!("golden/effect_trace_expire.bin"),
        Kind::FlagSet => include_bytes!("golden/effect_flag_set.bin"),
        Kind::QuotaSet => include_bytes!("golden/effect_quota_set.bin"),
        Kind::EphemeralConfigSet => include_bytes!("golden/effect_ephemeral_config_set.bin"),
        Kind::EphemeralConfigDelete => {
            include_bytes!("golden/effect_ephemeral_config_delete.bin")
        }
        Kind::GarbageAdd => include_bytes!("golden/effect_garbage_add.bin"),
        Kind::DeleteChunk => include_bytes!("golden/effect_delete_chunk.bin"),
        Kind::RequestIdsExpire => include_bytes!("golden/effect_request_ids_expire.bin"),
        Kind::ClusterVersionSet => include_bytes!("golden/effect_cluster_version_set.bin"),
        Kind::MembershipNote => include_bytes!("golden/effect_membership_note.bin"),
        Kind::TenantPurge => include_bytes!("golden/effect_tenant_purge.bin"),
    }
}

const ENTRY_FIXTURE: &[u8] = include_bytes!("golden/entry_message_path.bin");

/// `true` when this run is rewriting the fixtures (see the module header).
fn updating() -> bool {
    std::env::var("QUEEN_RSM_GOLDEN_UPDATE").as_deref() == Ok("1")
}

fn write_fixture(name: &str, bytes: &[u8]) {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("src/rsm/tests/golden")
        .join(name);
    std::fs::write(&path, bytes).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
}

fn hex(b: &[u8]) -> String {
    b.iter()
        .map(|x| format!("{x:02x}"))
        .collect::<Vec<_>>()
        .join("")
}

#[test]
fn every_kind_matches_its_golden_fixture() {
    let update = updating();
    for (kind, eff) in all_effect_samples() {
        let name = format!("effect_{}.bin", kind.name());
        let bytes = encode_effect(&eff);
        if update {
            write_fixture(&name, &bytes);
            continue;
        }
        let want = fixture(kind);
        assert_eq!(
            hex(want),
            hex(&bytes),
            "{name} changed. A change to a golden file is a FORMAT change: bump the kind's \
             version (§5.3) and only then rewrite the fixture with QUEEN_RSM_GOLDEN_UPDATE=1.",
        );
        // The other direction: the bytes ON DISK still decode to the sample.
        let (back, used) = decode_effect(want).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(used, want.len(), "{name}: bytes consumed");
        assert_eq!(back, eff, "{name}: decodes to another value");
    }
    assert!(
        !update,
        "fixtures were REWRITTEN; re-run without QUEEN_RSM_GOLDEN_UPDATE=1"
    );
}

#[test]
fn the_whole_entry_matches_its_golden_fixture() {
    let e = entry_sample();
    let bytes = encode_entry(&e).expect("the sample entry encodes");
    if updating() {
        write_fixture("entry_message_path.bin", &bytes);
        panic!("fixtures were REWRITTEN; re-run without QUEEN_RSM_GOLDEN_UPDATE=1");
    }
    assert_eq!(
        hex(ENTRY_FIXTURE),
        hex(&bytes),
        "entry_message_path.bin changed. That is a FORMAT change (§5.1): bump ENTRY_FORMAT \
         or the kind versions involved before rewriting the fixture.",
    );
    assert_eq!(decode_entry(ENTRY_FIXTURE).expect("decode the fixture"), e);
}

#[test]
fn the_entry_header_is_at_fixed_offsets() {
    // Pinned by hand, not by the encoder: a reader (recovery, a digest, a
    // future tool) may want the header without decoding the body.
    let b = ENTRY_FIXTURE;
    let body_len = u32::from_le_bytes(b[0..4].try_into().unwrap()) as usize;
    assert_eq!(ENTRY_HEADER_LEN + body_len, b.len());
    let body = &b[ENTRY_HEADER_LEN..];
    assert_eq!(
        u64::from_le_bytes(b[4..12].try_into().unwrap()),
        checksum(body)
    );
    assert_eq!(
        u16::from_le_bytes(body[0..2].try_into().unwrap()),
        ENTRY_FORMAT
    );
    assert_eq!(
        u32::from_le_bytes(body[2..6].try_into().unwrap()),
        VERSION_1 as u32
    );
    assert_eq!(
        i64::from_le_bytes(body[6..14].try_into().unwrap()),
        1_768_000_000_000_042
    );
    assert_eq!(u64::from_le_bytes(body[14..22].try_into().unwrap()), 7);
    assert_eq!(u64::from_le_bytes(body[22..30].try_into().unwrap()), 91_005);
    assert_eq!(u32::from_le_bytes(body[30..34].try_into().unwrap()), 3);
}

#[test]
fn the_smallest_effect_is_eight_bytes_of_header_and_nothing_else() {
    // The one fixture small enough to read by eye, spelled out so the frame
    // layout is pinned in prose as well as in bytes:
    //   kind   = 00 00        (Noop)
    //   version= 01 00        (VERSION_1)
    //   len    = 00 00 00 00  (an empty body)
    assert_eq!(
        fixture(Kind::Noop),
        &[0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00]
    );
    assert_eq!(fixture(Kind::Noop).len(), EFFECT_HEADER_LEN);

    // And one with a body, to pin the order of the header fields against a
    // kind id that is not zero: PartitionDelete { pid: 7 }.
    assert_eq!(
        fixture(Kind::PartitionDelete),
        &[
            0x06, 0x00, // kind 6
            0x01, 0x00, // version 1
            0x08, 0x00, 0x00, 0x00, // body len 8
            0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // pid 7, little-endian
        ]
    );
}
