FROM rust:1.88.0-alpine3.22@sha256:9dfaae478ecd298b6b5a039e1f2cc4fc040fc818a2de9aa78fa714dea036574d AS build

ARG SOURCE_DATE_EPOCH
ENV CARGO_INCREMENTAL=0 \
    SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH

RUN apk add --no-cache musl-dev=1.2.5-r12
WORKDIR /source
COPY supervisor/Cargo.toml supervisor/Cargo.lock ./
COPY supervisor/src ./src
RUN cargo build --release --locked \
    && cp target/release/queen-supervisor /queen-supervisor.first \
    && cargo clean \
    && cargo build --release --locked \
    && cmp /queen-supervisor.first target/release/queen-supervisor

FROM scratch AS artifact
COPY --from=build /queen-supervisor.first /queen-supervisor
