//! The operator chain's structural fingerprint.
//!
//! `config_hash` is what stops a redeployed pipeline from reinterpreting state
//! computed by a different one: change a window size or reorder the chain and
//! registration is refused until you pass `reset`.
//!
//! It must agree **byte for byte** with the JS, Go and Python SDKs, or the same
//! query redeployed in a different language would 409 against its own state.
//! That makes two things part of the contract rather than implementation
//! detail:
//!
//! * the JSON is `[{kind, ...config}]` with keys in **insertion order**, not
//!   sorted — so it is written out by hand here rather than through
//!   `serde_json::Map`, whose ordering depends on a cargo feature that another
//!   crate in the build could flip;
//! * user closures are deliberately **not** hashed. They cannot be serialized
//!   stably and change for cosmetic reasons; what corrupts state is a changed
//!   *shape*.

use sha2::{Digest, Sha256};

/// A JSON value in the small subset the config objects use.
#[derive(Debug, Clone, PartialEq)]
pub(crate) enum Json {
    Str(String),
    Int(i64),
    Bool(bool),
    StrArray(Vec<String>),
}

impl Json {
    fn write(&self, out: &mut String) {
        match self {
            Self::Str(s) => write_json_string(out, s),
            Self::Int(n) => out.push_str(&n.to_string()),
            Self::Bool(b) => out.push_str(if *b { "true" } else { "false" }),
            Self::StrArray(items) => {
                out.push('[');
                for (i, s) in items.iter().enumerate() {
                    if i > 0 {
                        out.push(',');
                    }
                    write_json_string(out, s);
                }
                out.push(']');
            }
        }
    }
}

/// One operator's ordered `(key, value)` description. `kind` is always first.
pub(crate) type OpDescription = Vec<(&'static str, Json)>;

/// `sha256(JSON.stringify(descriptions))`, hex-encoded lowercase.
pub(crate) fn config_hash(descriptions: &[OpDescription]) -> String {
    let json = render(descriptions);
    let mut hasher = Sha256::new();
    hasher.update(json.as_bytes());
    let digest = hasher.finalize();
    let mut out = String::with_capacity(64);
    for b in digest {
        out.push_str(&format!("{b:02x}"));
    }
    out
}

/// The exact bytes that get hashed. Separate from [`config_hash`] so tests can
/// assert on the JSON as well as the digest — a mismatch is far easier to read
/// as text than as a hex string.
pub(crate) fn render(descriptions: &[OpDescription]) -> String {
    let mut out = String::from("[");
    for (i, desc) in descriptions.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        out.push('{');
        for (j, (key, value)) in desc.iter().enumerate() {
            if j > 0 {
                out.push(',');
            }
            write_json_string(&mut out, key);
            out.push(':');
            value.write(&mut out);
        }
        out.push('}');
    }
    out.push(']');
    out
}

/// `JSON.stringify` escaping for a string: quotes, backslash, control
/// characters. Queue names and aggregate field names are user data, so this
/// cannot assume they are clean.
fn write_json_string(out: &mut String, s: &str) {
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\u{8}' => out.push_str("\\b"),
            '\u{c}' => out.push_str("\\f"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
}

#[cfg(test)]
mod tests {
    use super::*;

    fn s(v: &str) -> Json {
        Json::Str(v.to_string())
    }

    fn tumbling(seconds: i64, idle: i64) -> OpDescription {
        vec![
            ("kind", s("window-tumbling")),
            ("seconds", Json::Int(seconds)),
            ("gracePeriod", Json::Int(0)),
            ("idleFlushMs", Json::Int(idle)),
            ("eventTime", Json::Bool(false)),
            ("allowedLateness", Json::Int(0)),
            ("onLate", s("drop")),
        ]
    }

    // --- vectors captured from the JS SDK's configHashOf ---------------------
    //
    // Generated by running node against clients/client-js with the same chain
    // shapes. If any of these change, a stream registered by another SDK stops
    // matching this one's hash and re-registration 409s.

    #[test]
    fn map_only_matches_the_js_vector() {
        let ops = vec![vec![("kind", s("map"))]];
        assert_eq!(render(&ops), r#"[{"kind":"map"}]"#);
        assert_eq!(
            config_hash(&ops),
            "37ce851c2106e22ea6dbe56c95d26a491f2b8ed2e8b02d720c383f0439dbacdb"
        );
    }

    #[test]
    fn map_filter_sink_matches_the_js_vector() {
        let ops = vec![
            vec![("kind", s("map"))],
            vec![("kind", s("filter"))],
            vec![("kind", s("sink")), ("queue", s("out"))],
        ];
        assert_eq!(
            render(&ops),
            r#"[{"kind":"map"},{"kind":"filter"},{"kind":"sink","queue":"out"}]"#
        );
        assert_eq!(
            config_hash(&ops),
            "26e8e576fb2b4e60473d325efea14df31e80fd246930f4754557250236e49b69"
        );
    }

    #[test]
    fn tumbling_aggregate_sink_matches_the_js_vector() {
        let ops = vec![
            tumbling(60, 5000),
            vec![
                ("kind", s("aggregate")),
                (
                    "fields",
                    Json::StrArray(vec!["count".into(), "sum".into()]),
                ),
            ],
            vec![("kind", s("sink")), ("queue", s("out"))],
        ];
        assert_eq!(
            config_hash(&ops),
            "ed0617b6fa58103f0e4ac04443e6ea8e9a890a1ba5575b395c9d089300bfd743"
        );
    }

    #[test]
    fn reduce_with_initial_matches_the_js_vector() {
        let ops = vec![
            tumbling(5, 5000),
            vec![("kind", s("reduce")), ("hasInitial", Json::Bool(true))],
            vec![("kind", s("foreach"))],
        ];
        assert_eq!(
            config_hash(&ops),
            "16e4a7a92c3c6d0506dd92d6985abc6412190f92fd2e4432488bf59fa5556f89"
        );
    }

    #[test]
    fn gate_matches_the_js_vector() {
        let ops = vec![
            vec![("kind", s("gate"))],
            vec![("kind", s("sink")), ("queue", s("out"))],
        ];
        assert_eq!(
            config_hash(&ops),
            "5fd7e4a41b14cfa1442b1ae0dbd020cc1110911bc923b4dd42f5f925ac5b0b1d"
        );
    }

    #[test]
    fn sliding_matches_the_js_vector() {
        let ops = vec![
            vec![
                ("kind", s("window-sliding")),
                ("size", Json::Int(60)),
                ("slide", Json::Int(10)),
                ("gracePeriod", Json::Int(0)),
                ("idleFlushMs", Json::Int(5000)),
                ("eventTime", Json::Bool(false)),
                ("allowedLateness", Json::Int(0)),
                ("onLate", s("drop")),
            ],
            vec![("kind", s("reduce")), ("hasInitial", Json::Bool(true))],
        ];
        assert_eq!(
            config_hash(&ops),
            "4be87d543acabd81f0095490b6e93e4b4c73e8fa3cd84feeaac4f15f67c0e593"
        );
    }

    #[test]
    fn session_matches_the_js_vector() {
        let ops = vec![
            vec![
                ("kind", s("window-session")),
                ("gap", Json::Int(30)),
                ("gracePeriod", Json::Int(0)),
                ("idleFlushMs", Json::Int(1000)),
                ("eventTime", Json::Bool(false)),
                ("allowedLateness", Json::Int(0)),
                ("onLate", s("drop")),
            ],
            vec![("kind", s("reduce")), ("hasInitial", Json::Bool(true))],
        ];
        assert_eq!(
            config_hash(&ops),
            "3cd3a88348d114da37457f07ba7db276911a005615fff0ddf2308a95a4767b47"
        );
    }

    #[test]
    fn cron_matches_the_js_vector() {
        let ops = vec![
            vec![
                ("kind", s("window-cron")),
                ("every", s("minute")),
                ("gracePeriod", Json::Int(0)),
                ("idleFlushMs", Json::Int(30000)),
                ("eventTime", Json::Bool(false)),
                ("allowedLateness", Json::Int(0)),
                ("onLate", s("drop")),
            ],
            vec![("kind", s("reduce")), ("hasInitial", Json::Bool(true))],
        ];
        assert_eq!(
            config_hash(&ops),
            "0dbc1015f01f460eba75be6b67c07071e8cbb5466d13120eeb8afc96912d30e1"
        );
    }

    #[test]
    fn keyby_flatmap_matches_the_js_vector() {
        let ops = vec![vec![("kind", s("keyBy"))], vec![("kind", s("flatMap"))]];
        assert_eq!(
            config_hash(&ops),
            "0b5dafbf6a7ee537fd9fdf9a5423117b57fc5af6f5590b219fd63157a1af504e"
        );
    }

    // --- properties ---------------------------------------------------------

    #[test]
    fn key_order_is_insertion_order_not_alphabetical() {
        // The whole reason this module hand-writes JSON. Sorted keys would put
        // "gracePeriod" before "kind" and silently produce a different hash
        // from every other SDK.
        let rendered = render(&[tumbling(60, 5000)]);
        let kind_at = rendered.find("\"kind\"").unwrap();
        let grace_at = rendered.find("\"gracePeriod\"").unwrap();
        assert!(kind_at < grace_at, "{rendered}");
    }

    #[test]
    fn a_changed_window_size_changes_the_hash() {
        assert_ne!(
            config_hash(&[tumbling(60, 5000)]),
            config_hash(&[tumbling(30, 5000)])
        );
    }

    #[test]
    fn a_reordered_chain_changes_the_hash() {
        let a = vec![vec![("kind", s("map"))], vec![("kind", s("filter"))]];
        let b = vec![vec![("kind", s("filter"))], vec![("kind", s("map"))]];
        assert_ne!(config_hash(&a), config_hash(&b));
    }

    #[test]
    fn a_different_sink_queue_changes_the_hash() {
        let a = vec![vec![("kind", s("sink")), ("queue", s("out-a"))]];
        let b = vec![vec![("kind", s("sink")), ("queue", s("out-b"))]];
        assert_ne!(config_hash(&a), config_hash(&b));
    }

    #[test]
    fn an_empty_chain_hashes_the_empty_array() {
        assert_eq!(render(&[]), "[]");
        // sha256("[]")
        assert_eq!(
            config_hash(&[]),
            "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945"
        );
    }

    #[test]
    fn strings_are_escaped_like_json_stringify() {
        let mut out = String::new();
        write_json_string(&mut out, "a\"b\\c");
        assert_eq!(out, "\"a\\\"b\\\\c\"");

        let mut out = String::new();
        write_json_string(&mut out, "tab\there\nnew");
        assert_eq!(out, "\"tab\\there\\nnew\"");

        // Control characters below 0x20 take the \u form, matching
        // JSON.stringify — a raw byte there would be invalid JSON.
        let mut out = String::new();
        write_json_string(&mut out, "\u{1}");
        assert_eq!(out, "\"\\u0001\"");

        let mut out = String::new();
        write_json_string(&mut out, "\u{8}\u{c}\r");
        assert_eq!(out, "\"\\b\\f\\r\"");
    }

    #[test]
    fn a_queue_name_with_a_quote_does_not_break_the_json() {
        let ops = vec![vec![("kind", s("sink")), ("queue", s(r#"we"ird"#))]];
        let rendered = render(&ops);
        assert_eq!(rendered, r#"[{"kind":"sink","queue":"we\"ird"}]"#);
        // and it still parses as JSON
        let _: serde_json::Value = serde_json::from_str(&rendered).unwrap();
    }
}
